spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mdmdb
    username: mdmuser
    password: mdmpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
